const fs = require('fs');
const path = require('path');

// This script generates js/env.js from system environment variables during the build step.
// It allows Vercel's "Vault" variables to be available to the static frontend.

const targetFile = path.join(__dirname, '../js/env.js');
const dotEnvFile = path.join(__dirname, '../.env');

// Simple helper to get env from process or .env file
function getEnv(key) {
    if (process.env[key]) return process.env[key];
    
    // Fallback to reading .env file manually (no dotenv dependency)
    if (fs.existsSync(dotEnvFile)) {
        const lines = fs.readFileSync(dotEnvFile, 'utf8').split('\n');
        const match = lines.find(line => line.startsWith(`${key}=`));
        if (match) return match.split('=')[1].trim();
    }
    return '';
}

const envContent = `// This file is auto-generated by scripts/generate-env.js during deployment.
window.process = {
  env: {
    API_KEY: "${getEnv('API_KEY')}",
    AUTH_DOMAIN: "${getEnv('AUTH_DOMAIN')}",
    PROJECT_ID: "${getEnv('PROJECT_ID')}",
    STORAGE_BUCKET: "${getEnv('STORAGE_BUCKET')}",
    MESSAGING_SENDER_ID: "${getEnv('MESSAGING_SENDER_ID')}",
    APP_ID: "${getEnv('APP_ID')}",
  }
};`;

// Ensure the directory exists
const targetDir = path.dirname(targetFile);
if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
}

// Write the env.js file
try {
    fs.writeFileSync(targetFile, envContent);
    console.log('✅ js/env.js has been successfully generated.');
} catch (err) {
    console.error('❌ Error generating js/env.js:', err);
    process.exit(1);
}
